version: '2'
services:
  frontend:
    build: frontend
    depends_on:
      - api
    restart: always
    ports:
      - "0.0.0.0:39089:80"
    volumes:
      - $PWD/frontend/html:/usr/share/nginx/html
  api:
    build: backend
    restart: always
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - SENTRY_DSN=$SENTRY_DSN
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - $PWD/backend/main.py:/app/main.py
