version: '2'
services:
  frontend:
    build: frontend
    depends_on:
      - api
    restart: always
    ports:
      - "0.0.0.0:39081:80"
  api:
    build: backend
    restart: always
    environment:
      - SENTRY_DSN=$SENTRY_DSN
  bot:
    build: bot
    depends_on:
      - api
    restart: always
    environment:
      - GMAP_API_KEY=$GMAP_API_KEY
      - WHAPI_TOKEN=$WHAPI_TOKEN
      - WHAPI_GROUP=$WHAPI_GROUP
